### PR TITLE
Added tanh.js to the repository -- it was missing

### PR DESCRIPTION
**Pull request by abramhindle**

### CODE REVIEW

**Comment by charlieroberts** [comment]
Thanks! But there's some weird changes in the dist directory... probably due to babel / browserify I think. Most aren't a big deal, but a couple are a bit worrisome... for example, dist/gen.js on line 118, where the closing parenthesis doesn't come until after a bunch of single-line comments. I guess that's OK to the JS parser? Do the tests all still pass?

**Comment by abramhindle** [comment]
Well tbqh I don't think we should be committing the dist. It did not pass tests as far as I can tell, I've never seen it pass tests either.

**Comment by charlieroberts** [comment]
OK, cool, I'm going to pull these and get rid of dist. I think. All the tests run against dist (because I want to run against the final compiled ES5 files)... I guess it's a reasonable assumption that anyone wanting to run tests will have compiled first, right?

**Comment by charlieroberts** [comment]
when I say "get rid of dist" I mean remove all the files from the repo with the exception of the browserified library.

**Comment by charlieroberts** [comment]
OK, done. Good feedback about removing the files from dist, thanks!

**Pull request merged**
